package com.example.attachment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-17T14:23:35.622+05:30
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://attachment.example.com/", name = "GetAttachmentImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface GetAttachmentImpl {

    @RequestWrapper(localName = "getAttachment", targetNamespace = "http://attachment.example.com/", className = "com.example.attachment.GetAttachment")
    @WebMethod
    @ResponseWrapper(localName = "getAttachmentResponse", targetNamespace = "http://attachment.example.com/", className = "com.example.attachment.GetAttachmentResponse")
    public void getAttachment(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
