package com.example.attachment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-17T14:23:35.647+05:30
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "GetAttachmentImplService", 
                  wsdlLocation = "http://localhost:8181/cxf/receivemessage/attachment?wsdl",
                  targetNamespace = "http://attachment.example.com/") 
public class GetAttachmentImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://attachment.example.com/", "GetAttachmentImplService");
    public final static QName GetAttachmentImplPort = new QName("http://attachment.example.com/", "GetAttachmentImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8181/cxf/receivemessage/attachment?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetAttachmentImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8181/cxf/receivemessage/attachment?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetAttachmentImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetAttachmentImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAttachmentImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetAttachmentImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetAttachmentImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetAttachmentImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns GetAttachmentImpl
     */
    @WebEndpoint(name = "GetAttachmentImplPort")
    public GetAttachmentImpl getGetAttachmentImplPort() {
        return super.getPort(GetAttachmentImplPort, GetAttachmentImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAttachmentImpl
     */
    @WebEndpoint(name = "GetAttachmentImplPort")
    public GetAttachmentImpl getGetAttachmentImplPort(WebServiceFeature... features) {
        return super.getPort(GetAttachmentImplPort, GetAttachmentImpl.class, features);
    }

}
