package com.fusesource.test.mtom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Progress FUSE Services Framework 2.2.11-fuse-00-00
 * Tue Mar 10 11:32:40 IST 2015
 * Generated source version: 2.2.11-fuse-00-00
 * 
 */
 
@WebService(targetNamespace = "http://www.fusesource.com/test/mtom", name = "MtomTest")
@XmlSeeAlso({com.fusesource.test.mtom.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MtomTest {

    @WebResult(name = "doMtomResponse", targetNamespace = "http://www.fusesource.com/test/mtom/v1", partName = "parameters")
    @WebMethod(action = "http://www.fusesource.com/test/mtom/do")
    public com.fusesource.test.mtom.v1.DoMtomResponse doMtom(
        @WebParam(partName = "parameters", name = "doMtomRequest", targetNamespace = "http://www.fusesource.com/test/mtom/v1")
        com.fusesource.test.mtom.v1.DoMtomRequest parameters
    );
}
